services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    image: manage-contract:1.0.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.33.228:3306/manage_contract
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567